name: Build RedPill DSM loader

on:
  release:
    types: published
  push:
    branches:
      - master
    paths:
      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: started
    

jobs:
  redpill:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    name: Build RedPill lkm and load
    steps:
      - uses: actions/checkout@v2.1.0
        name: checkout src
        id: checkout
        with:
          submodules: 'true'
      
      - name: fill my synoinfo
        env:
          SN: ${{ secrets.SN }}
          TWINE_PASSWORD: ${{ env.SN }}
        run: |
            echo ${{ secrets.SN }}
            echo ${{ secrets.MAC1 }}
            echo "${{ env.SN }}"
            echo ${{ env.MAC1 }}
            echo "${{ env.MAC1 }}"
            echo "$SN"
            
            sed -i 's/17A0PDN123456/${{ env.SN }}/g' ./user_config.DS918+.json
            sed -i 's/ENVMAC1/${{ env.ENVMAC1 }}/g' ./user_config.DS918+.json
            sed -i 's/ENVMAC2/${{ env.ENVMAC2 }}/g' ./user_config.DS918+.json
            exit 12
       
      - name: Build DS918+ 7.0.1
        id: build-ds918-70
        run: |
            bash build-ds918-7.0.1.sh

      - name: Archive DS918+ 7.0.1 loader image
        uses: actions/upload-artifact@v2
        with:
          name: redpill-DS918+_7.0.1-loader
          path: output/redpill-DS918+_7.0*.img
