name: Build RedPill DSM loader

on:
  release:
    types: published
  push:
    branches:
      - master
    paths:
      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: started
    

jobs:
  redpill:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    name: Build RedPill lkm and load
    steps:
      - uses: actions/checkout@v2.1.0
        name: checkout src
        id: checkout
        with:
          submodules: 'true'
      
      - name: fill my synoinfo
        run: |
            sed -i 's/17A0PDN123456/${{ secrets.SN }}/g' ./user_config.DS918+.json
            sed -i 's/ENVMAC1/${{ secrets.MAC1 }}/g' ./user_config.DS918+.json
            sed -i 's/ENVMAC2/${{ secrets.MAC2 }}/g' ./user_config.DS918+.json
            cat ./user_config.DS918+.json

       
      - name: Build DS918+ 7.0.1
        id: build
        run: |
            bash build-ds918-7.0.1.sh
            echo "::set-output name=status::success"
            

      - name: Archive DS918+ 7.0.1 loader image
        uses: actions/upload-artifact@v2
        if: steps.build.outputs.status == 'success' && !cancelled()
        with:
          name: redpill-DS918+_7.0.1-loader
          path: output/redpill-DS918+_7.0*.img
